# Enable to log Damage/Element Types of the damage instance and reduction info of the damage.
# DO NOT ENABLE IN PRODUCTION SERVER, IT SPAMS THE CONSOLE
debug: false

# Acceptable stat value: -2147483648 ~ 100 (Except 0 because why?)
# Negative value will make the mob take more damage instead.
# Putting value that's not in the range will cause the stat to be ignored..... and spams the console when you reload :suiwheeze:
mythic_mobs:
  # Template here, replace v_dummy with MythicMobs internal mob name, remove the stat if you don't need it, don't put 0. :amewtf:
  #   v_dummy:
  #     damage_reduction: 10
  #     magic_reduction: 20
  #     physical_reduction: 30
  #     weapon_reduction: 40
  #     skill_reduction: 50
  #     projectile_reduction: 60
  #     unarmed_reduction: 70
  #     on_hit_reduction: 80
  #     minion_reduction: 90
  #     dot_reduction: 100
  #     elements:
  #       void_reduction: -50
  v_dummy:
    damage_reduction: 10
    magic_reduction: 20
    physical_reduction: 30
    weapon_reduction: 20
    skill_reduction: 10
    projectile_reduction: 20
    unarmed_reduction: 10
    on_hit_reduction: 20
    minion_reduction: 10
    dot_reduction: 20
    elements:
      void_reduction: -100
  test01:
    damage_reduction: 100
    elements:
      void_reduction: 10